/**
 * Unit tests for buildSituationalConfiguration.
 *
 * Run on their own:
 *   node --import tsx --test src/workflows/fit-shared/fit-configuration/tests/build-situational-configuration.test.ts
 */
import assert from "node:assert/strict";
import { test } from "node:test";
import {
  buildSituationalConfiguration,
  DEFAULT_CAPELLA_CLUSTER_VERSION,
  DEFAULT_CBDINO_SETTINGS,
} from "../build-situational-configuration.js";

test("the config carries the auto-generated marker and performer port", () => {
  const config = buildSituationalConfiguration();
  assert.equal(config["//"], "Auto-generated by fit-cli");
  assert.deepEqual(config.performerPorts, [8060]);
});

test("a custom performer port is honoured", () => {
  const config = buildSituationalConfiguration(DEFAULT_CBDINO_SETTINGS, 8070);
  assert.deepEqual(config.performerPorts, [8070]);
});

test("columnar/analytics tests are excluded by default", () => {
  const config = buildSituationalConfiguration();
  assert.deepEqual(config.excludeTests, ["columnar"]);
});

test("a definition fitConfig piece can opt back into columnar tests", () => {
  const config = buildSituationalConfiguration(DEFAULT_CBDINO_SETTINGS, 8060, {
    excludeTests: [],
  });
  assert.deepEqual(config.excludeTests, []);
});

test("the cbdino and files blocks are merged under situational", () => {
  const config = buildSituationalConfiguration({
    version: "7.2",
    cbDinoClusterAppPath: "/opt/cbdinocluster",
    enablePrivateEndpoint: true,
  });
  assert.deepEqual(config.situational, {
    cbdino: {
      version: "7.2",
      cbDinoClusterAppPath: "/opt/cbdinocluster",
      enablePrivateEndpoint: true,
    },
    files: { outputDirectory: "results" },
  });
});

test("the config emits a files block and no database block", () => {
  const situational = buildSituationalConfiguration().situational as Record<string, unknown>;
  assert.deepEqual(situational.files, { outputDirectory: "results" });
  assert.equal(situational.database, undefined);
});

test("a fitConfig piece that reintroduces situational.database is rejected", () => {
  assert.throws(
    () =>
      buildSituationalConfiguration(DEFAULT_CBDINO_SETTINGS, 8060, {
        situational: { database: { jdbc: "jdbc:postgresql://example/perf" } },
      }),
    /sets situational\.database/,
  );
});

test("a gcp deployer and region are forwarded into the cbdino block", () => {
  const config = buildSituationalConfiguration({
    version: "8.0",
    cbDinoClusterAppPath: "cbdinocluster",
    enablePrivateEndpoint: true,
    deployer: "gcp",
    region: "us-west1",
  });
  assert.deepEqual(config.situational, {
    cbdino: {
      version: "8.0",
      cbDinoClusterAppPath: "cbdinocluster",
      enablePrivateEndpoint: true,
      deployer: "gcp",
      region: "us-west1",
    },
    files: { outputDirectory: "results" },
  });
});

test("cbdino settings default to a DEFAULT_CAPELLA_CLUSTER_VERSION cluster on the PATH binary", () => {
  const config = buildSituationalConfiguration() as {
    situational: { cbdino: typeof DEFAULT_CBDINO_SETTINGS };
  };
  assert.deepEqual(config.situational.cbdino, DEFAULT_CBDINO_SETTINGS);
  assert.equal(config.situational.cbdino.version, DEFAULT_CAPELLA_CLUSTER_VERSION);
});

test("the placeholder clusterAccess is present but flagged as ignored", () => {
  const config = buildSituationalConfiguration();
  const access = config.clusterAccess as Record<string, unknown>;
  assert.match(String(access["//"]), /cbdino/i);
});

test("a definition fitConfig piece is layered last and can override generated fields", () => {
  const config = buildSituationalConfiguration(DEFAULT_CBDINO_SETTINGS, 8060, {
    excludeTests: ["openshift"],
    extra: { added: true },
  });
  assert.deepEqual(config.excludeTests, ["openshift"]);
  assert.deepEqual(config.extra, { added: true });
});
