/**
 * Step: build the FITConfiguration object from the answers gathered earlier.
 * Pure logic — no file IO — so it's easy to unit test (see
 * tests/build-fit-configuration.test.ts). Modelled on the example configs in
 * transactions-fit-performer/test-driver/.
 *
 * Run on its own:
 *   bun src/fit/functional/util/build-fit-configuration.ts
 *
 * Prints a sample generated config as JSON.
 */
import { isMain, runCli } from "../../../util/non-fit/cli.js";
import { mergeConfigPieces, type ConfigPiece, type PieceData } from "../../../util/non-fit/config-pieces.js";
import type { SelectedCluster } from "../../../cluster/cluster-select/cluster-select.js";
import { DEFAULT_PERFORMER_PORT } from "../../performers/util/performer-port.js";
import type { FitConnectionSpec, ConnectionScheme } from "../../shared/definition/types.js";

/** Marks a config as generated by fit-cli. */
export const AUTO_GENERATED_MARKER = "Auto-generated by fit-cli";

/**
 * The runtime-resolved inputs needed to enable the test-driver's cluster-creating
 * functional tests (those annotated `@RequiresClusterCreating`). The performer
 * gates these on `resourceCreation.cluster` being present, and that block requires
 * both a cbdinocluster path (the binary on the box where the test-driver runs) and
 * a preferred server version — see transactions-fit-performer's FITConfiguration.md.
 */
export interface ClusterCreatingConfig {
  /** Absolute path to cbdinocluster on the execution host. */
  cbdinoclusterPath: string;
  /** Concrete (alias-resolved) server version to create, e.g. "8.0.1-4654". */
  version: string;
}

/**
 * The `resourceCreation` piece that turns on cluster-creating functional tests.
 * Both sub-keys are mandatory on the performer side (it throws otherwise). Tests
 * are free to override `preferredCluster` when they need a specific version.
 */
export function resourceCreationPiece(clusterCreating: ClusterCreatingConfig): PieceData {
  return {
    resourceCreation: {
      "//": "Enables cluster-creating functional tests (@RequiresClusterCreating).",
      cluster: {
        cbdinocluster: { path: clusterCreating.cbdinoclusterPath },
        preferredCluster: { version: clusterCreating.version },
      },
    },
  };
}

/**
 * Return the first hostname from a (potentially comma-separated) hostname list.
 * The connection string can carry multiple bootstrap nodes, but REST and similar
 * single-host fields must be given just one address.
 */
export function firstHostname(defaultHostname: string): string {
  return defaultHostname.split(",")[0]?.trim() ?? defaultHostname.trim();
}

/**
 * Produce a FITConfiguration object for a selected cluster. Capella clusters
 * (internal or production) use DNS SRV resolution, skip bucket creation and
 * don't expose the FIT proxy; self-managed clusters get the localhost-style
 * layout.
 *
 * `performerPort` is the host port the performer listens on (the `performerPorts`
 * entry test-driver connects to); it defaults to {@link DEFAULT_PERFORMER_PORT}.
 */
/**
 * The clusterAccess for a CNG / OpenShift cluster.
 *
 * On OpenShift (ROSA), Couchbase is exposed via TLS-passthrough routes on port 443 only.
 * There is no external KV (memcached) port — only HTTPS management and the couchbase2
 * gateway.  The driver therefore cannot use a classic couchbase:// connection (KV bootstrap
 * would stall), so we use the flat `connectionString: couchbase2://…` structure matching
 * the GHA workflow (fit-app-deployment PR #123).  The test-driver uses couchbase2 directly
 * and skips bucket creation (the bucket is pre-created by cbdinocluster / the cluster spec).
 *
 * The REST field uses the management UI hostname (bare, no port) + explicit port 443 so the
 * test-driver's HTTP client reaches the management API on the correct port.
 */
function cngClusterAccess(cluster: SelectedCluster & { cng: NonNullable<SelectedCluster["cng"]> }): PieceData {
  const firstHost = firstHostname(cluster.defaultHostname);
  // Strip any :port suffix — rest.hostname must be a bare hostname; the port goes in rest.port.
  const restHostname = firstHost.replace(/:\d+$/, "");
  // Extract the explicit port from defaultHostname to use as rest.port (defaults to 18091 for
  // couchbases:// but OpenShift routes expose on 443).
  const portMatch = /:\d+$/.exec(firstHost);
  const restPort = portMatch ? parseInt(portMatch[0].slice(1), 10) : undefined;
  return {
    defaultHostname: cluster.defaultHostname,
    connectionString: cluster.cng.performerConnectionString,
    tls: cluster.cng.tls,
    username: cluster.credentials.username,
    password: cluster.credentials.password,
    rest: { hostname: restHostname, resolveDnsSrv: false, ...(restPort !== undefined ? { port: restPort } : {}) },
    ssh: null,
    "//": "The FIT proxy does not yet support couchbase2.",
    proxy: null,
  };
}

export function generatedFitConfigurationPiece(
  cluster: SelectedCluster,
  performerPort: number = DEFAULT_PERFORMER_PORT,
  analytics = false,
  isLocal = false,
): ConfigPiece {
  if (cluster.cng) {
    return {
      label: "fit-cli generated CNG defaults",
      data: {
        "//": AUTO_GENERATED_MARKER,
        clusterAccess: cngClusterAccess({ ...cluster, cng: cluster.cng }),
        performerPorts: [performerPort],
        excludeTests: ["situational"],
        // The bucket is pre-created in the CouchbaseCluster spec; the driver must not try to
        // create it via classic management (there is no external KV or mgmt port on OpenShift).
        skipBucketCreation: true,
      },
    };
  }

  if (analytics) {
    // Analytics (Enterprise Analytics / Capella Analytics): the driver connects
    // classically for admin, but the connection specifics (load balancer, the
    // SDK's analytics endpoint, proxy) come from the definition's
    // fitConfig.config.clusterAccess, which merges over these defaults. We emit
    // only the baseline here, and skip bucket creation — Analytics manages its own
    // data; there is no KV bucket to create.
    return {
      label: "fit-cli generated Analytics defaults",
      data: {
        "//": AUTO_GENERATED_MARKER,
        clusterAccess: {
          defaultHostname: cluster.defaultHostname,
          connectionString: `${cluster.scheme}://\${defaultHostname}`,
          username: cluster.credentials.username,
          password: cluster.credentials.password,
          tls: cluster.tls,
          // For Enterprise Analytics (load-balanced cbdinocluster): use the first node
          // hostname so REST talks to a single node; no DNS SRV. For Capella Analytics
          // (cloud, cbdinocluster cloud deployer): use the ${defaultHostname} template
          // and resolve DNS SRV, matching how the cloud cluster exposes its endpoint.
          rest: {
            hostname: cluster.analyticsLoadBalancerHost
              ? firstHostname(cluster.defaultHostname)
              : "${defaultHostname}",
            resolveDnsSrv: !cluster.analyticsLoadBalancerHost,
          },
          // Columnar / Analytics does not support direct SSH access.
          ssh: null,
          // proxy.hostname: where the performer reaches the FIT proxy. The performer
          // runs in Docker, so it must use host.docker.internal — not localhost, which
          // inside the container is the container itself (every query would then fail
          // with "Failed to connect to localhost:<mapped-port>"). Matches the
          // operational self-managed proxy. (The analytics reference example uses
          // localhost only because there the performer runs on the host, not in Docker.)
          //
          // proxy.clusterHostname: where the FIT proxy forwards TO. It defaults to
          // defaultHostname, which here is the driver's comma-joined node list — and
          // the proxy can't dial a comma-separated string (DNS lookup fails, it falls
          // back to the literal string as one host → "unexpected end of stream"). For a
          // load-balanced Enterprise Analytics cluster the proxy must forward to the
          // single nginx LB host, so pin it explicitly when we know it. For Capella
          // Analytics (cloud, single endpoint) no override is needed.
          proxy: {
            hostname: "host.docker.internal",
            ...(cluster.analyticsLoadBalancerHost
              ? { clusterHostname: cluster.analyticsLoadBalancerHost }
              : {}),
          },
        },
        performerPorts: [performerPort],
        excludeTests: ["situational"],
        skipBucketCreation: true,
      },
    };
  }

  const isCapella = cluster.flavour !== "self-managed";
  // A PrivateLink private DNS hostname has no `_couchbases._tcp` SRV record (only
  // Capella's public DNS does), so SRV-based bootstrap discovery must be disabled
  // even though the cluster otherwise looks like Capella.
  const resolveDnsSrv = isCapella && !cluster.privateEndpoint;

  const clusterAccess: PieceData = {
    defaultHostname: cluster.defaultHostname,
    connectionString: `${cluster.scheme}://\${defaultHostname}`,
    username: cluster.credentials.username,
    password: cluster.credentials.password,
    tls: cluster.tls,
    rest: {
      hostname: isCapella ? "${defaultHostname}" : firstHostname(cluster.defaultHostname),
      resolveDnsSrv,
      ...(isCapella ? { port: 18091 } : {}),
    },
    ssh: null,
    proxy: isCapella
      ? null
      : {
          "//":
            "The performer is running in Docker and needs to be able to connect to the FIT proxy (the test-driver) running on the host machine",
          hostname: "host.docker.internal",
        },
  };

  // Capella clusters have no direct SSH access, so the ssh-tagged tests can't run;
  // realCapella tests need setup this generated config doesn't provide. Excluding
  // both mirrors the FITConfiguration.capella.example.json layout. Running against
  // Capella from a local machine (rather than an EC2 instance in the same region)
  // adds enough network latency to fail tests tagged requiresLowLatencyConnection
  // (see e.g. RangeScanTest in transactions-fit-performer), so exclude those too.
  const excludeTests = isCapella
    ? ["situational", "ssh", "realCapella", ...(isLocal ? ["requiresLowLatencyConnection"] : [])]
    : ["situational"];

  const data: PieceData = {
    "//": AUTO_GENERATED_MARKER,
    clusterAccess,
    performerPorts: [performerPort],
    excludeTests,
  };

  if (isCapella) {
    data.skipBucketCreation = true;
  } else {
    // numReplicas >= 1 is required for FTS tests to pass.
    data.bucketConfig = { numReplicas: 1, bucketType: "couchbase", storage: "couchstore" };
  }

  return { label: "fit-cli generated defaults", data };
}

export function runtimeFitConfigurationPiece(cluster: SelectedCluster): ConfigPiece {
  const firstHost = firstHostname(cluster.defaultHostname);
  const restHostname = firstHost.replace(/:\d+$/, "");
  const portMatch = /:\d+$/.exec(firstHost);
  const restPort = portMatch ? parseInt(portMatch[0].slice(1), 10) : undefined;
  return {
    label: "fit-cli runtime cluster fields",
    data: {
      clusterAccess: {
        defaultHostname: cluster.defaultHostname,
        rest: {
          hostname: restHostname,
          ...(restPort !== undefined ? { port: restPort } : {}),
        },
      },
    },
  };
}

/**
 * Build a `clusterAccess.connectionString` for a given scheme and cluster.
 * For `couchbase2`, the host comes from `cluster.cng.performerConnectionString`
 * (already a full `couchbase2://host:port` URL) when available, otherwise falls
 * back to `couchbase2://${defaultHostname}`.  Classic schemes use the
 * `${defaultHostname}` template which FIT resolves at runtime.
 */
function connectionStringForScheme(scheme: ConnectionScheme, cluster: SelectedCluster): string {
  if (scheme === "couchbase2") {
    return cluster.cng?.performerConnectionString ?? `couchbase2://\${defaultHostname}`;
  }
  return `${scheme}://\${defaultHostname}`;
}

/**
 * Build a `clusterAccess` override piece from a {@link FitConnectionSpec}.
 * When the spec has only `scheme`/`tls` (no `driver`/`performer`), a flat
 * `connectionString` is written.  When `driver` or `performer` is present, the
 * split `driver` / `performer` structure from FITConfiguration.md is written.
 */
function connectionSpecPiece(spec: FitConnectionSpec, cluster: SelectedCluster): ConfigPiece {
  const hasDriverOrPerformer = spec.driver !== undefined || spec.performer !== undefined;

  const tlsFor = (tls: FitConnectionSpec["tls"] | undefined, fallback: FitConnectionSpec["tls"]): PieceData | null | undefined => {
    const resolved = tls !== undefined ? tls : fallback;
    if (resolved === null) return null;
    if (resolved === undefined) return undefined;
    return resolved as PieceData;
  };

  let clusterAccess: PieceData;
  if (hasDriverOrPerformer) {
    // Split mode: separate driver and performer blocks.
    const driverScheme = spec.driver?.scheme ?? spec.scheme;
    const performerScheme = spec.performer?.scheme ?? spec.scheme;
    const driverTls = tlsFor(spec.driver?.tls, spec.tls);
    const performerTls = tlsFor(spec.performer?.tls, spec.tls);
    clusterAccess = {
      ...(driverScheme !== undefined
        ? { driver: { connectionString: connectionStringForScheme(driverScheme, cluster), ...(driverTls !== undefined ? { tls: driverTls } : {}) } }
        : {}),
      ...(performerScheme !== undefined
        ? { performer: { connectionString: connectionStringForScheme(performerScheme, cluster), ...(performerTls !== undefined ? { tls: performerTls } : {}) } }
        : {}),
    };
  } else {
    // Flat mode: single connectionString.
    const scheme = spec.scheme;
    const tls = tlsFor(spec.tls, undefined);
    clusterAccess = {
      ...(scheme !== undefined ? { connectionString: connectionStringForScheme(scheme, cluster) } : {}),
      ...(tls !== undefined ? { tls } : {}),
    };
  }

  return { label: "fitConfig connection spec", data: { clusterAccess } };
}

/**
 * Build the final FITConfiguration object for a cluster.
 *
 * - `fitConfigPiece`: merged in after the generated defaults (printed to console).
 * - `connection`: if provided, overrides the auto-generated `clusterAccess`
 *   connection fields (scheme, tls, driver/performer split).
 * - `patchPiece`: merged in last (highest priority); NOT included in the logged
 *   output — use for verbose or sensitive values (certificates, tokens).
 */
export function buildFitConfiguration(
  cluster: SelectedCluster,
  performerPort: number = DEFAULT_PERFORMER_PORT,
  fitConfigPiece?: PieceData,
  connection?: FitConnectionSpec,
  patchPiece?: PieceData,
  analytics = false,
  isLocal = false,
): Record<string, unknown> {
  const hasConfig = fitConfigPiece !== undefined || connection !== undefined;
  const merged = mergeConfigPieces([
    generatedFitConfigurationPiece(cluster, performerPort, analytics, isLocal),
    ...(fitConfigPiece ? [{ label: "definition fitConfig piece", data: fitConfigPiece }] : []),
    ...(hasConfig ? [runtimeFitConfigurationPiece(cluster)] : []),
    ...(connection ? [connectionSpecPiece(connection, cluster)] : []),
    ...(patchPiece ? [{ label: "definition patch piece", data: patchPiece }] : []),
  ]);
  if (analytics && cluster.analyticsLoadBalancerHost) {
    pointAnalyticsPerformerAtLoadBalancer(merged, cluster.analyticsLoadBalancerHost);
  }
  return merged;
}

/**
 * Point the Analytics SDK performer at the nginx load balancer. The performer's
 * connection string is authored (in the preset or by the wizard) with the
 * `${defaultHostname}` token, which FIT resolves to the driver's multi-seed node
 * list — fine for the driver's couchbase:// string, but an HTTP/SDK URL needs a
 * single host, so okhttp throws UnknownHostException on the comma-separated list.
 * Rewrite just the performer's host to the concrete load-balancer address,
 * preserving the scheme/port the author chose (http://…:8095 for the Enterprise
 * Analytics SDK; couchbases:// for a Columnar SDK). The driver and REST keep the
 * node list / first node, which they want. Mutates `config` in place.
 */
function pointAnalyticsPerformerAtLoadBalancer(config: Record<string, unknown>, loadBalancerHost: string): void {
  const clusterAccess = config.clusterAccess as Record<string, unknown> | undefined;
  const performer = clusterAccess?.performer as Record<string, unknown> | undefined;
  const connectionString = performer?.connectionString;
  if (typeof connectionString === "string" && connectionString.includes("${defaultHostname}")) {
    performer!.connectionString = connectionString.replaceAll("${defaultHostname}", loadBalancerHost);
  }
}

if (isMain(import.meta.url)) {
  runCli(() => {
    const sample = buildFitConfiguration({
      scheme: "couchbase",
      defaultHostname: "localhost",
      flavour: "self-managed",
      credentials: { username: "Administrator", password: "password" },
      tls: null,
    });
    console.log(JSON.stringify(sample, null, 2));
    return Promise.resolve();
  });
}
