/**
 * The shape of a `fit` YAML definition file.
 */
import type { PortInUsePolicy } from "../../performers/util/performer-port.js";
import type { CapellaCloudProvider, CbdinoclusterDef } from "../../../cluster/cluster-create/build-cluster-def.js";
import type { ClusterExistsPolicy } from "../../../cluster/cluster-create/cluster-exists-policy.js";
import type { PieceData } from "../../../util/non-fit/config-pieces.js";

export const FIT_DEFINITION_TYPE = "fit";
export const CURRENT_FIT_DEFINITION_VERSION = 1;
export const FIT_RUN_TYPES = ["functional", "situational", "analytics-functional"] as const;

export type FitRunType = (typeof FIT_RUN_TYPES)[number];
export type FitConfigPiece = PieceData;
export type ClusterTls = null | { insecure: true } | { certPath: string };

export interface ConnectionClusterSetup {
  connectionString: string;
  username: string;
  password: string;
  tls?: ClusterTls;
}

export type UseExistingClusterSetup = Record<string, never>;

/**
 * How to prepare `~/.cbdinocluster` on the box before allocating.
 *
 * Carries an editable `args` string — the arguments passed to `cbdinocluster init`
 * (e.g. `--auto --disable-k8s --docker-network fit`) so the box self-installs its
 * config. fit-cli appends the GitHub credentials at runtime (kept out of the
 * definition file). `configPatch` is merged onto `~/.cbdinocluster` after init
 * runs, for config `cbdinocluster init` can't express via flags — e.g.
 * situational's `capella`/`aws` blocks, or CNG's `k8s` block (injected at runtime
 * from the logged-in OpenShift context). `config` uploads a verbatim object as
 * `~/.cbdinocluster` (legacy back-compat; not generated by fit-cli). At most one of
 * `args`/`config` is present; `configPatch` requires `args`.
 */
export interface CbdinoclusterInitSetup {
  args?: string;
  config?: PieceData;
  configPatch?: PieceData;
}

/**
 * Build cbdinocluster from a pull request or branch instead of downloading the
 * latest release. Exactly one of `pr` (PR number) or `branch` (branch name) must
 * be given, against the canonical `couchbaselabs/cbdinocluster` repo; `repo`
 * overrides to a fork (`owner/repo`).
 */
export type CbdinoclusterSourceGit = { repo?: string } & ({ pr: number; branch?: never } | { pr?: never; branch: string });

/**
 * Where to get the cbdinocluster binary. When absent the latest published GitHub
 * release is used (default behaviour). When present, the binary is built from the
 * PR's or branch's HEAD on the remote box itself — always the right OS/arch, no
 * local binary needed.
 */
export interface CbdinoclusterSource {
  git: CbdinoclusterSourceGit;
}

/**
 * Declares that this cluster should be created as a Capella cloud cluster via
 * cbdinocluster's `cloud` deployer. `cloudProvider` specifies where Capella
 * should deploy the underlying infrastructure; `environment` selects the
 * Capella control-plane (a key under `capella` in environments.json5 — e.g.
 * "dev", "stage"). fit-cli derives the cbdinocluster init args and deployer
 * from this block at runtime; neither needs to appear in the definition file.
 */
export interface CapellaClusterSetup {
  cloudProvider: CapellaCloudProvider;
  /** Capella environment to create this cluster in. Defaults to "dev". */
  environment?: string;
  /**
   * Set up a private endpoint (AWS PrivateLink or GCP PSC) connection to this
   * cluster after it's created, and connect the FIT test-driver/performer over
   * it instead of the public endpoint. Requires the instance to have
   * `aws.privateEndpoint` or `gcp.privateEndpoint` set, matching this cluster's
   * `cloudProvider` (see {@link AwsInstanceSetup}/{@link GcpInstanceSetup}).
   * Empty for now (just a marker) but kept as an object — not a boolean — so
   * provider-specific settings can be added later without a breaking schema
   * change (see {@link PrivateEndpointSetup}).
   */
  privateEndpoint?: PrivateEndpointSetup;
}

export interface CbdinoclusterSetup {
  config: CbdinoclusterDef;
  onClusterExists?: ClusterExistsPolicy;
  deployer?: string;
  /** When present, this cluster is a Capella cloud cluster. */
  capella?: CapellaClusterSetup;
}

/**
 * Per-instance setup applied once to the box before any cluster or run. The
 * cbdinocluster `init` lives here (not under each cluster) because `cbdinocluster
 * init` configures `~/.cbdinocluster` once per instance — every cluster on the
 * instance then allocates against that same config.
 */
export interface InstanceSetup {
  cbdinocluster?: {
    /** How to init ~/.cbdinocluster. Omit to run the standard docker-only init. */
    init?: CbdinoclusterInitSetup;
  };
  /**
   * Capella environment this instance's clusters are created in (a key under
   * `capella` in environments.json5 — e.g. "dev", "stage"). Lives here because
   * `cbdinocluster init` configures one `~/.cbdinocluster` (and so one Capella
   * identity) per instance/box. Defaults to "dev".
   */
  capellaEnvironment?: string;
}

/**
 * Present when the instance is launched so it can reach a Capella private
 * endpoint (AWS PrivateLink or GCP PSC). On AWS this attaches the VPC default
 * SG (opened intra-VPC by terraform), which the PrivateLink endpoint also
 * lands in; AWS credentials are forwarded to the box the same way situational
 * runs do, so cbdinocluster's `private-endpoints setup-link` (which creates
 * the VPC endpoint) can authenticate as fit-cli-role — no separate IAM
 * instance profile is needed. On GCP the box is tagged so the
 * fit-cli-allow-private-endpoint firewall rule (terraform/gcp/firewall.tf)
 * admits traffic from the PSC endpoint; the attached fit-cli-gcp service
 * account already has the GCP permissions setup-link needs, so no separate
 * credential upload is required. Pair with `capella.privateEndpoint: {}` on
 * the cluster.
 *
 * Empty for now (just a marker) but kept as an object — not a boolean — so
 * provider-specific settings can be added later without a breaking schema change.
 */
export type PrivateEndpointSetup = Record<string, never>;

export interface AwsInstanceSetup {
  instanceType?: string;
  privateEndpoint?: PrivateEndpointSetup;
}

/**
 * A GCP Compute Engine instance, reached over an IAP-tunneled SSH connection
 * (see util/non-fit/iap-target.ts).
 */
export interface GcpInstanceSetup {
  instanceType?: string;
  /** GCP's PSC counterpart of {@link AwsInstanceSetup.privateEndpoint}. */
  privateEndpoint?: PrivateEndpointSetup;
}

export type InstanceMode =
  | { aws: AwsInstanceSetup }
  | { gcp: GcpInstanceSetup }
  | { localhost: Record<string, never> };

export interface RepoSetup {
  gerritRef?: string;
}

export interface ReposSetup {
  "transactions-fit-performer"?: RepoSetup;
}

export interface SharedSetup {
  repos?: ReposSetup;
  cbdinocluster?: {
    /** Where to get the binary, applied to every instance in this run. Omit to use the latest published release. */
    source?: CbdinoclusterSource;
  };
}

export interface PerformerSetup {
  /**
   * Full prebuilt performer image, `<sdk>-fit-performer:<tag>` (e.g.
   * `java-fit-performer:main` or `java-fit-performer:refs-changes-18-195818-7`).
   * The SDK is derived from the image prefix; only JVM and C++ SDKs publish
   * these images. fit-cli prepends the GHCR registry/owner at run time.
   */
  image: string;
  port?: number;
  onPortInUse?: PortInUsePolicy;
}

/** Named test presets that expand to a set of test classes. */
export const TEST_PRESETS = ["all", "all-transactions", "all-non-transactions", "standard-qe"] as const;
export type TestPreset = (typeof TEST_PRESETS)[number];

export interface MavenOptions {
  args?: string[];
  runDisabledTests?: boolean;
}

/**
 * Which test-driver tests a run executes. The final set is the union of every
 * preset's expansion with the explicit `classes`. Presets like
 * `all-transactions` are expanded against the listed tests at run time; an
 * `all` preset (or omitting both keys) means "run everything". `classes` lists
 * fully-qualified test class names (or `Class#method` selectors) to add on top.
 * `packages` lists Java package prefixes; each is expanded to a `pkg.*` Maven
 * wildcard selector and unioned with `classes`.
 */
export interface TestsSection {
  presets?: TestPreset[];
  packages?: string[];
  classes?: string[];
  /**
   * Replaces the built-in default excluded Maven groups outright. Mutually
   * exclusive with `addToDefaultExcludedGroups`.
   */
  excludedGroups?: string[];
  /**
   * Adds these groups on top of the built-in defaults (the common case when a
   * preset just needs one extra exclusion). Mutually exclusive with
   * `excludedGroups`. Composes with `reincludeDefaultExcludedGroups`.
   */
  addToDefaultExcludedGroups?: string[];
  /**
   * Removes these groups from the built-in default exclusions (e.g. a release
   * preset opting back into `slow` tests that every other tier skips).
   * Mutually exclusive with `excludedGroups`. Composes with
   * `addToDefaultExcludedGroups`.
   */
  reincludeDefaultExcludedGroups?: string[];
  maven?: MavenOptions;
}

export const SITUATIONAL_DATABASE_MODES = ["files"] as const;
export type SituationalDatabaseMode = (typeof SITUATIONAL_DATABASE_MODES)[number];

export interface SituationalDatabaseSetup {
  /**
   * files: driver writes result files and we upload them to the results S3 bucket
   * after the run, where a downstream job loads them into the results database.
   * Needs the files-only driver change (transactions-fit-performer I3f285a9e) -
   * point setup.repos at it until it merges.
   */
  mode: SituationalDatabaseMode;
}

/** Object marker, matching {@link PrivateEndpointSetup}'s empty-object convention. */
export type SituationalCngSetup = Record<string, never>;

export interface SituationalSection {
  database: SituationalDatabaseSetup;
  /**
   * When present, situational's cbdino-managed cluster is built via the Couchbase
   * Autonomous Operator (CAO) / CNG gateway (OpenShift) instead of a Capella cloud
   * cluster.
   */
  cng?: SituationalCngSetup;
  /**
   * Set up a private-endpoint (AWS PrivateLink or GCP PSC, matching the
   * instance's cloud) connection to the Capella cluster cbdino creates for
   * this situational run, and connect the test-driver over it instead of the
   * public endpoint. Requires the instance to have `aws.privateEndpoint` or
   * `gcp.privateEndpoint` set to match (see {@link AwsInstanceSetup},
   * {@link GcpInstanceSetup}). Unlike {@link CapellaClusterSetup.privateEndpoint},
   * this doesn't drive fit-cli's own private-endpoint setup — it's wired straight
   * into the FIT test-driver's `situational.cbdino.enablePrivateEndpoint`
   * flag (plus `deployer`/`region` for gcp), and the driver's own CbDinoManager
   * does the private-endpoint setup and connection-string swap. Empty for now
   * (just a marker) but kept as an object — not a boolean — for consistency
   * with {@link PrivateEndpointSetup}'s other uses.
   */
  privateEndpoint?: PrivateEndpointSetup;
  /**
   * Couchbase Server version cbdino should deploy for this run's self-managed
   * Capella cluster, e.g. "8.0" or "7.6". Capella's supported versions lag
   * self-managed and are coarser-grained (a plain release line rather than a
   * cb-alias like "8.0-stable" or a pinned build) — see
   * `environments.json5`'s `capellaClusterVersion`. Defaults to the
   * situational default version (currently "7.6") when omitted. Mutually
   * exclusive with `cng` (CNG pins its own cluster version from
   * environments.json5) and with the run-level `versions` shorthand — see
   * {@link SituationalRun.versions}.
   */
  version?: string;
}

export interface FunctionalRun {
  type: "functional";
  fitConfig?: ResolvedFitConfig | string;
  tests: TestsSection;
  /** Run this entry N times in sequence against the same cluster. */
  repeat?: number;
}

export interface SituationalRun {
  type: "situational";
  fitConfig?: ResolvedFitConfig | string;
  situational: SituationalSection;
  tests: TestsSection;
  /** Run this entry N times in sequence. */
  repeat?: number;
  /**
   * Run this same situational spec once per listed Couchbase Server version,
   * in sequence — shorthand for duplicating the whole run block just to vary
   * `situational.version` (e.g. `["8.0", "7.6"]`). Mutually exclusive with
   * `repeat` and with `situational.version`/`situational.cng`.
   */
  versions?: string[];
}

/**
 * A functional run that tests an Analytics product — Enterprise Analytics or
 * Capella Analytics — via the `columnar-test-driver` Maven module (query,
 * connection and auth tests) rather than the operational `test-driver`. Like
 * {@link FunctionalRun} it is cluster-bound; what is being tested is expressed by:
 *   - the cluster: a cbdinocluster `columnar: true` block (a self-managed
 *     Enterprise Analytics cluster), or a connection to a Capella Analytics cluster;
 *   - the performer image: a Columnar SDK or an Enterprise Analytics SDK;
 *   - the connection details on the fitConfig (driver vs performer), as for CNG.
 */
export interface AnalyticsFunctionalRun {
  type: "analytics-functional";
  fitConfig?: ResolvedFitConfig | string;
  tests: TestsSection;
  /** Run this entry N times in sequence against the same cluster. */
  repeat?: number;
}

export type FitRun = FunctionalRun | SituationalRun | AnalyticsFunctionalRun;

export interface SessionLifetime {
  performer: PerformerSetup;
  runs: FitRun[];
}

export interface ClusterLifetime {
  connection?: ConnectionClusterSetup;
  useExisting?: UseExistingClusterSetup;
  cbdinocluster?: CbdinoclusterSetup;
  clusterConfig?: string;
  sessions: SessionLifetime[];
}

export interface ClusterConfigRef {
  id: string;
  cbdinocluster?: CbdinoclusterSetup;
  connection?: ConnectionClusterSetup;
  useExisting?: UseExistingClusterSetup;
}

/** Connection scheme for a FIT driver or performer. */
export type ConnectionScheme = "couchbase" | "couchbases" | "couchbase2";

/** Per-component (driver or performer) scheme and TLS overrides. */
export interface SchemeAndTls {
  /** Protocol scheme for the SDK connection string. */
  scheme?: ConnectionScheme;
  /**
   * TLS config for this component.  `null` disables TLS; omit to inherit the
   * top-level tls setting.
   */
  tls?: { insecure?: boolean; cert?: string } | null;
}

/**
 * Declares the SDK connection scheme(s) fit-cli should write into
 * `clusterAccess` in FITConfiguration.json.  When absent, fit-cli infers the
 * scheme from the cluster type (`cao` → couchbase2, else classic).
 *
 * `scheme` / `tls` at the top level apply to both driver and performer unless
 * overridden by the `driver` / `performer` sub-objects — matching the
 * FITConfiguration `driver` / `performer` override structure described in
 * FITConfiguration.md.
 */
export interface FitConnectionSpec {
  scheme?: ConnectionScheme;
  tls?: { insecure?: boolean; cert?: string } | null;
  /** Override the scheme/TLS for only the test-driver side. */
  driver?: SchemeAndTls;
  /** Override the scheme/TLS for only the performer side. */
  performer?: SchemeAndTls;
}

export interface FitConfigRef {
  id: string;
  /** Fields merged into FITConfiguration.json and printed to the console. */
  config?: FitConfigPiece;
  /**
   * Declares the connection scheme(s) fit-cli should use when generating
   * `clusterAccess` in FITConfiguration.json.  When absent, fit-cli infers
   * from the cluster type.
   */
  connection?: FitConnectionSpec;
  /**
   * Raw FITConfiguration.json partial merged in last (highest priority).
   * Unlike `config`, this is NOT printed to the console — use it for values
   * that are verbose or sensitive (certificates, tokens).
   */
  patch?: FitConfigPiece;
}

/**
 * The resolved form of a fitConfig entry — carries `config`, `connection`, and
 * `patch` together.  In a parsed `FitRun`, `fitConfig` starts as
 * `ResolvedFitConfig | string`; `resolveDefinitionRefs` replaces the string
 * (ref id) with the full resolved object.
 */
export interface ResolvedFitConfig {
  /** Merged into FITConfiguration.json and printed to the console. */
  config?: PieceData;
  /** Declares the connection scheme(s); overrides fit-cli's auto-detection. */
  connection?: FitConnectionSpec;
  /** Merged into FITConfiguration.json last (highest priority); NOT printed to the console. */
  patch?: PieceData;
}

export type InstanceLifetime =
  & InstanceMode
  & {
    setup?: InstanceSetup;
    clusters: ClusterLifetime[];
    clusterlessSessions?: SessionLifetime[];
  };

export interface FitDefinition {
  version: number;
  type: typeof FIT_DEFINITION_TYPE;
  description?: string;
  instances: InstanceLifetime[];
  setup?: SharedSetup;
  clusterConfigs?: ClusterConfigRef[];
  fitConfigs?: FitConfigRef[];
}
